import { AgentContract } from "../src/types/index";
import { PROOFFLEET_GEMINI_MODEL } from "./gemini";

const DETERMINISTIC_RUNTIME = "deterministic-runtime";

export const FLEET_AGENTS: AgentContract[] = [
  {
    id: "orchestrator",
    name: "Fleet Commander",
    codename: "ORCHESTRATOR-01",
    title: "Mission Orchestration & Task Planning",
    description: "Decomposes a mission into explicit phases and coordinates role execution. Gemini may assist the planning narrative, but the Orchestrator cannot mutate external state or issue the final truth verdict.",
    model: PROOFFLEET_GEMINI_MODEL,
    capabilities: ["Task Decomposition", "Dependency Graphing", "Agent Dispatch", "Planning Narrative"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "Compass",
    color: "#3B82F6",
  },
  {
    id: "scout",
    name: "Scout",
    codename: "SCOUT-02",
    title: "Context & Grounding",
    description: "Produces clearly marked Gemini context when no grounding tool is available and only reports grounded=true when a real grounding tool returns sources. Gemini output is agent context, never authoritative runtime evidence.",
    model: PROOFFLEET_GEMINI_MODEL,
    capabilities: ["Context Extraction", "Grounding Boundary", "Source Attribution", "Output Hashing"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "Search",
    color: "#06B6D4",
  },
  {
    id: "builder",
    name: "Builder",
    codename: "BUILDER-03",
    title: "Artifact Specification & Build Preparation",
    description: "Builds deterministic mission artifacts and reports only checks that actually ran. It may prepare write/execute work but does not certify external effects as true.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Artifact Specification", "Schema Validation", "Build Preparation", "Check Reporting"],
    permissions: ["read", "write", "execute"],
    riskLevel: "MEDIUM",
    status: "idle",
    avatarIcon: "Cpu",
    color: "#8B5CF6",
  },
  {
    id: "analyst",
    name: "Analyst",
    codename: "ANALYST-04",
    title: "Evidence Metrics & Logical Analysis",
    description: "Computes deterministic metrics over available mission/evidence snapshots and flags analytical findings without manufacturing confidence or truth scores.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Evidence Metrics", "Deterministic Analysis", "Consistency Checks", "Hash Calculations"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "BarChart3",
    color: "#EC4899",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    codename: "SENTINEL-05",
    title: "Security & Permission Assessment",
    description: "Scans visible mission/evidence strings for configured secret patterns and checks the real fleet permissions against the enforced role matrix. It cannot grant consent.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Secret Pattern Scan", "Permission Conformance", "Least-Privilege Checks", "Security Findings"],
    permissions: ["read", "verify"],
    riskLevel: "HIGH",
    status: "idle",
    avatarIcon: "ShieldAlert",
    color: "#EF4444",
  },
  {
    id: "auditor",
    name: "Auditor",
    codename: "AUDITOR-06",
    title: "Evidence Integrity Auditor",
    description: "Exports and checks evidence/receipt integrity snapshots. It does not mutate the target, assign truth-confidence scores, or replace the independent Judge.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Evidence Snapshot", "SHA-256 Integrity", "Receipt Inspection", "Audit Export"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "CheckCircle2",
    color: "#10B981",
  },
  {
    id: "gatekeeper",
    name: "Gatekeeper",
    codename: "GATEKEEPER-07",
    title: "Consent & Human-in-the-Loop Governance",
    description: "Derives the concrete mutating OperationSpec and opens an explicit human consent request bound to that exact operation. It never auto-approves or executes the operation itself.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Operation Binding", "Consent Request", "Risk Justification", "Approval Boundary"],
    permissions: ["read", "consent_gate"],
    riskLevel: "CRITICAL",
    status: "idle",
    avatarIcon: "Lock",
    color: "#F59E0B",
  },
  {
    id: "operator",
    name: "Operator",
    codename: "OPERATOR-08",
    title: "Authorized Effect Execution",
    description: "Executes only an explicitly approved operation through the configured effect executor and projects authoritative readback provenance. It cannot issue the final Judge verdict.",
    model: DETERMINISTIC_RUNTIME,
    capabilities: ["Authorized Execution", "Idempotency", "Readback-before-Retry", "Effect Provenance"],
    permissions: ["read", "write", "execute"],
    riskLevel: "MEDIUM",
    status: "idle",
    avatarIcon: "Terminal",
    color: "#64748B",
  },
];
