import { AgentContract } from "../src/types/index";

export const FLEET_AGENTS: AgentContract[] = [
  {
    id: "orchestrator",
    name: "Fleet Commander",
    codename: "ORCHESTRATOR-01",
    title: "Mission Orchestration & Task Planning",
    description: "Decomposes complex human missions into a verifiable directed acyclic graph (DAG), coordinates inter-agent contracts, and synthesizes final truth verdicts.",
    model: "gemini-3.7-flash",
    capabilities: ["Task Decomposition", "Dependency Graphing", "Agent Dispatch", "Final Synthesis"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "Compass",
    color: "#3B82F6",
  },
  {
    id: "researcher",
    name: "Scout",
    codename: "SCOUT-02",
    title: "Grounding & Intelligence Extraction",
    description: "Extracts grounded facts, queries external APIs and verified knowledge graphs, and attaches provenance citations to every gathered claim.",
    model: "gemini-3.7-flash",
    capabilities: ["Search Grounding", "Source Attribution", "Fact Extraction", "Corroboration"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "Search",
    color: "#06B6D4",
  },
  {
    id: "engineer",
    name: "Builder",
    codename: "BUILDER-03",
    title: "Code Synthesis & System Engineering",
    description: "Designs, generates, and validates robust TypeScript/Cloud code, executes static lint tests, and prepares deterministic build artifacts.",
    model: "gemini-3.7-flash",
    capabilities: ["Code Generation", "Static Analysis", "Refactoring", "Test Automation"],
    permissions: ["read", "write", "execute"],
    riskLevel: "MEDIUM",
    status: "idle",
    avatarIcon: "Cpu",
    color: "#8B5CF6",
  },
  {
    id: "analyst",
    name: "Analyst",
    codename: "ANALYST-04",
    title: "Data Reasoning & Quantitative Logic",
    description: "Processes multi-dimensional metrics, runs anomaly detection algorithms, performs cryptographic hash calculations, and validates logical consistency.",
    model: "gemini-3.7-flash",
    capabilities: ["Statistical Analysis", "Anomaly Detection", "Logic Verification", "Matrix Computation"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "BarChart3",
    color: "#EC4899",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    codename: "SENTINEL-05",
    title: "Security, Guardrails & Threat Assessment",
    description: "Performs strict zero-trust vulnerability scanning, secret leak detection, prompt injection defense, and enforces least-privilege security policies.",
    model: "gemini-3.7-flash",
    capabilities: ["Zero-Trust Scanning", "Vulnerability Audit", "Secret Detection", "Guardrail Enforcement"],
    permissions: ["read", "verify", "consent_gate"],
    riskLevel: "HIGH",
    status: "idle",
    avatarIcon: "ShieldAlert",
    color: "#EF4444",
  },
  {
    id: "auditor",
    name: "Auditor",
    codename: "AUDITOR-06",
    title: "Truth & Evidence Hash Auditor",
    description: "Audits claims against gathered evidence, verifies cryptographic Merkle/SHA-256 chain integrity, and assigns empirical truth confidence scores.",
    model: "gemini-3.7-flash",
    capabilities: ["Evidence Verification", "SHA-256 Hash Validation", "Truth Scoring", "Hallucination Defense"],
    permissions: ["read", "verify"],
    riskLevel: "LOW",
    status: "idle",
    avatarIcon: "CheckCircle2",
    color: "#10B981",
  },
  {
    id: "gatekeeper",
    name: "Gatekeeper",
    codename: "GATEKEEPER-07",
    title: "Consent & Human-in-the-Loop Governance",
    description: "Intercepts all high-impact actions, state mutations, and external write calls; enforces mandatory human consent before permitting execution.",
    model: "gemini-3.7-flash",
    capabilities: ["Consent Interception", "Risk Tier Evaluation", "Approval Management", "Policy Governance"],
    permissions: ["read", "consent_gate"],
    riskLevel: "CRITICAL",
    status: "idle",
    avatarIcon: "Lock",
    color: "#F59E0B",
  },
  {
    id: "operator",
    name: "Operator",
    codename: "OPERATOR-08",
    title: "Action Execution & Delivery",
    description: "Carries out approved operations, seals the final cryptographically signed audit ledger, and exposes telemetry metrics to observability endpoints.",
    model: "gemini-3.1-flash-lite",
    capabilities: ["Action Dispatch", "Ledger Sealing", "Telemetry Tracking", "Export Packaging"],
    permissions: ["read", "write", "execute"],
    riskLevel: "MEDIUM",
    status: "idle",
    avatarIcon: "Terminal",
    color: "#64748B",
  },
];
