import React, { useState } from "react";
import {
  AlertTriangle,
  Check,
  CheckCircle2,
  Copy,
  FileCheck,
  ShieldCheck,
} from "lucide-react";
import { Mission } from "../types";
import { deriveTruthVerdictPresentation } from "./truthVerdictPresentation";

interface TruthVerificationReportProps {
  mission: Mission | null;
}

const TONE_CLASSES = {
  verified: {
    surface: "border-emerald-200 bg-emerald-50/30",
    icon: "border-emerald-100 bg-emerald-50 text-emerald-600",
    status: "border-emerald-200 bg-emerald-50 text-emerald-800",
    emphasis: "text-emerald-900",
    note: "text-emerald-700",
  },
  blocked: {
    surface: "border-amber-200 bg-amber-50/30",
    icon: "border-amber-100 bg-amber-50 text-amber-700",
    status: "border-amber-200 bg-amber-50 text-amber-900",
    emphasis: "text-amber-950",
    note: "text-amber-800",
  },
  contradicted: {
    surface: "border-rose-200 bg-rose-50/30",
    icon: "border-rose-100 bg-rose-50 text-rose-700",
    status: "border-rose-200 bg-rose-50 text-rose-900",
    emphasis: "text-rose-950",
    note: "text-rose-800",
  },
  not_verified: {
    surface: "border-slate-300 bg-slate-50",
    icon: "border-slate-200 bg-slate-100 text-slate-700",
    status: "border-slate-300 bg-slate-100 text-slate-800",
    emphasis: "text-slate-950",
    note: "text-slate-700",
  },
} as const;

export const TruthVerificationReport: React.FC<TruthVerificationReportProps> = ({ mission }) => {
  const [copied, setCopied] = useState(false);

  if (!mission || !mission.finalVerdict) {
    return null;
  }

  const { finalVerdict } = mission;
  const presentation = deriveTruthVerdictPresentation(
    finalVerdict.judgeVerdict.verdict,
    finalVerdict.integrityVerified,
    finalVerdict.compliancePassed,
  );
  const tone = TONE_CLASSES[presentation.tone];

  const handleCopyReport = () => {
    const markdown = [
      "# ProofFleet " + presentation.heading,
      "**Mission:** " + mission.title,
      "**Goal:** " + mission.inputGoal,
      "**Status:** " + presentation.status,
      "**Timestamp:** " + (mission.finishedAt || "not finished"),
      "",
      "## Truth & Cryptographic Integrity",
      "- **Judge Verdict:** " + finalVerdict.judgeVerdict.verdict + " — " + finalVerdict.judgeVerdict.rationale,
      "- **Cryptographic Chain Integrity:** " + (finalVerdict.integrityVerified ? "INTACT" : "FAILED"),
      "- **Policy Compliance:** " + (finalVerdict.compliancePassed ? "PASSED" : "FAILED"),
      "- **Final SHA-256 Digest:** " + finalVerdict.chainHashDigest,
      "",
      "## Summary",
      finalVerdict.summary,
      "",
      "## Recommendations",
      finalVerdict.recommendations.map((recommendation) => "- " + recommendation).join("\n"),
      "",
      "---",
      "*Generated by ProofFleet Agentic Substrate (Google All Things Agentic Hackathon)*",
    ].join("\n");

    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={"rounded-2xl border p-5 shadow-xs " + tone.surface}>
      <div className="mb-4 flex flex-col justify-between gap-3 border-b border-slate-200/70 pb-4 sm:flex-row sm:items-center">
        <div className="flex items-center gap-2.5">
          <div className={"flex h-8 w-8 items-center justify-center rounded-lg border " + tone.icon}>
            {presentation.isVerified ? <FileCheck className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}
          </div>
          <div>
            <h2 className={"text-sm font-bold " + tone.emphasis}>{presentation.heading}</h2>
            <p className={"text-xs " + tone.note}>{presentation.description}</p>
          </div>
        </div>

        <button
          onClick={handleCopyReport}
          className="self-start rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 shadow-2xs transition-all hover:bg-slate-50 sm:self-auto"
        >
          <span className="inline-flex items-center gap-1.5">
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Copy className="h-3.5 w-3.5 text-slate-500" />}
            {copied ? "Report Copied!" : "Copy Markdown Report"}
          </span>
        </button>
      </div>

      <div className="mb-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
        <div className={"rounded-xl border p-3 " + tone.status}>
          <span className="block text-[10px] font-bold uppercase tracking-wider">Scoped verdict</span>
          <div className={"mt-1 text-lg font-black " + tone.emphasis}>{presentation.status}</div>
          <p className={"mt-1 text-[10px] leading-snug " + tone.note}>{finalVerdict.judgeVerdict.rationale}</p>
        </div>

        <div className={"rounded-xl border p-3 " + (finalVerdict.integrityVerified
          ? "border-blue-200 bg-blue-50/60"
          : "border-rose-200 bg-rose-50")}>
          <span className="block text-[10px] font-bold uppercase tracking-wider text-slate-600">Chain integrity</span>
          <div className={"mt-1.5 flex items-center gap-1.5 text-sm font-bold " + (finalVerdict.integrityVerified ? "text-blue-900" : "text-rose-900")}>
            {finalVerdict.integrityVerified
              ? <ShieldCheck className="h-4 w-4 text-blue-600" />
              : <AlertTriangle className="h-4 w-4 text-rose-600" />}
            <span>{finalVerdict.integrityVerified ? "Intact (SHA-256)" : "FAILED — NOT VERIFIED"}</span>
          </div>
        </div>

        <div className={"rounded-xl border p-3 " + (finalVerdict.compliancePassed
          ? "border-slate-200 bg-slate-50"
          : "border-rose-200 bg-rose-50")}>
          <span className="block text-[10px] font-bold uppercase tracking-wider text-slate-600">Policy compliance</span>
          <div className={"mt-1.5 flex items-center gap-1.5 text-sm font-bold " + (finalVerdict.compliancePassed ? "text-slate-900" : "text-rose-900")}>
            {finalVerdict.compliancePassed
              ? <CheckCircle2 className="h-4 w-4 text-slate-600" />
              : <AlertTriangle className="h-4 w-4 text-rose-600" />}
            <span>{finalVerdict.compliancePassed ? "Policy gates passed" : "Policy gates failed"}</span>
          </div>
        </div>
      </div>

      <div className="space-y-3 rounded-xl border border-slate-200 bg-white/70 p-4 text-xs text-slate-700">
        <div>
          <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">
            Executive summary
          </span>
          <p className="leading-relaxed text-slate-900">{finalVerdict.summary}</p>
        </div>

        <div>
          <span className="mb-1 block text-[10px] font-bold uppercase tracking-wider text-slate-400">
            Recommendations
          </span>
          <ul className="space-y-1 text-slate-700">
            {finalVerdict.recommendations.map((recommendation, index) => (
              <li key={index} className="flex items-center gap-2">
                <span className={"h-1.5 w-1.5 rounded-full " + (presentation.isVerified ? "bg-emerald-500" : "bg-slate-500")} />
                <span>{recommendation}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex items-center justify-between border-t border-slate-200/60 pt-2 text-[10px] text-slate-500">
          <span className="mr-2 truncate font-mono">Final Hash: {finalVerdict.chainHashDigest}</span>
          <span className={"shrink-0 font-semibold " + tone.note}>
            {presentation.isVerified ? "Verified only after Judge + integrity + policy gates" : "Not a verified mission claim"}
          </span>
        </div>
      </div>
    </div>
  );
};
