import React, { useState } from "react";
import {
  FileCheck,
  CheckCircle2,
  Copy,
  Check,
  Download,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { Mission } from "../types";

interface TruthVerificationReportProps {
  mission: Mission | null;
}

export const TruthVerificationReport: React.FC<TruthVerificationReportProps> = ({
  mission,
}) => {
  const [copied, setCopied] = useState(false);

  if (!mission || !mission.finalVerdict) {
    return null;
  }

  const { finalVerdict } = mission;

  const handleCopyReport = () => {
    const markdown = `# ProofFleet Verifiable Multi-Agent Audit Report
**Mission:** ${mission.title}
**Goal:** ${mission.inputGoal}
**Status:** Completed
**Timestamp:** ${mission.finishedAt}

## Truth & Cryptographic Integrity Verdict
- **Judge Verdict:** ${finalVerdict.judgeVerdict.verdict} — ${finalVerdict.judgeVerdict.rationale}
- **Cryptographic Chain Integrity:** ${finalVerdict.integrityVerified ? "VERIFIED (100% Intact)" : "FAILED"}
- **Zero-Trust Policy Compliance:** ${finalVerdict.compliancePassed ? "PASSED" : "FAILED"}
- **Final SHA-256 Digest:** \`${finalVerdict.chainHashDigest}\`

## Summary
${finalVerdict.summary}

## Recommendations
${finalVerdict.recommendations.map((r) => `- ${r}`).join("\n")}

---
*Generated by ProofFleet Agentic Substrate (Google All Things Agentic Hackathon)*`;

    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-xs">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4 pb-4 border-b border-slate-100">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-emerald-50 border border-emerald-100 flex items-center justify-center text-emerald-600">
            <FileCheck className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-slate-900">
              Verified Mission Audit Report
            </h2>
            <p className="text-xs text-slate-500">
              Cryptographically sealed multi-agent consensus report
            </p>
          </div>
        </div>

        <button
          onClick={handleCopyReport}
          className="self-start sm:self-auto flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-200 bg-slate-50 hover:bg-white text-xs font-semibold text-slate-700 transition-all shadow-2xs"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-600" />
              <span>Report Copied!</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5 text-slate-500" />
              <span>Copy Markdown Report</span>
            </>
          )}
        </button>
      </div>

      {/* Metrics Row */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
        <div className="p-3 rounded-xl bg-emerald-50/50 border border-emerald-200">
          <span className="text-[10px] font-bold text-emerald-700 uppercase tracking-wider block">
            Judge Verdict
          </span>
          <div className="flex items-baseline gap-1 mt-1">
            <span className="text-lg font-black text-emerald-900">
              {finalVerdict.judgeVerdict.verdict}
            </span>
          </div>
          <p className="text-[10px] text-emerald-700 mt-1 leading-snug">
            {finalVerdict.judgeVerdict.rationale}
          </p>
        </div>

        <div className="p-3 rounded-xl bg-blue-50/50 border border-blue-200">
          <span className="text-[10px] font-bold text-blue-700 uppercase tracking-wider block">
            Chain Integrity
          </span>
          <div className="flex items-center gap-1.5 mt-1.5 text-blue-900 font-bold text-sm">
            <ShieldCheck className="w-4 h-4 text-blue-600" />
            <span>{finalVerdict.integrityVerified ? "Intact (SHA-256)" : "FAILED"}</span>
          </div>
        </div>

        <div className="p-3 rounded-xl bg-slate-50 border border-slate-200">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">
            Policy Compliance
          </span>
          <div className="flex items-center gap-1.5 mt-1.5 text-slate-900 font-bold text-sm">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            <span>{finalVerdict.compliancePassed ? "No Violations Detected" : "Violations Detected"}</span>
          </div>
        </div>
      </div>

      {/* Summary */}
      <div className="text-xs text-slate-700 space-y-3 bg-slate-50/50 p-4 rounded-xl border border-slate-200">
        <div>
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
            Executive Summary
          </span>
          <p className="leading-relaxed text-slate-900">{finalVerdict.summary}</p>
        </div>

        <div>
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
            Sealed Recommendations
          </span>
          <ul className="space-y-1 text-slate-700">
            {finalVerdict.recommendations.map((rec, i) => (
              <li key={i} className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="pt-2 border-t border-slate-200/60 flex items-center justify-between text-[10px] text-slate-500">
          <span className="font-mono truncate mr-2">
            Final Hash: {finalVerdict.chainHashDigest}
          </span>
          <span className="shrink-0 font-semibold text-emerald-600">
            Cryptographically Sealed (SHA-256)
          </span>
        </div>
      </div>
    </div>
  );
};
