import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { CloudRunAdapter } from '../server/adapters/gcp/cloudrun';
import { ConsentEngine } from '../server/consent/consentEngine';
import { canonicalJson, sha256Hex } from '../server/evidence/canonicalJson';
import { bindExecutionToCredential, parseGoogleWifCredentialEvidence, type GoogleWifCredentialEvidence } from '../server/evidence/executionIdentity';
import { buildLiveGcpProofPlan, type LiveGcpProofPlan } from '../server/gcp/liveProof';
import { FirestoreOperatorExecutor, createRealFirestoreEffectStore } from '../server/ops/firestoreEffect';
const RECEIPT_PATH='gcp-live-proof-receipt.json';
type ProofOutcome='OBSERVED'|'BLOCKED_BY_MISSING_EVIDENCE'|'CONTRADICTED';
interface ReceiptBase{schemaVersion:'prooffleet.gcp-live-proof.v3';sourceRevision:string;executionIdentity:LiveGcpProofPlan['executionIdentity'];credentialEvidence:GoogleWifCredentialEvidence|null;executionCredentialBindingHash:string|null;projectId:string;region:string;cloudRunService:string;firestoreCollection:string;operationId:string;generatedAt:string}
interface LiveProofReceiptBody extends ReceiptBase{outcome:ProofOutcome;reason:string;cloudRun:Record<string,unknown>|null;firestore:Record<string,unknown>|null}
function nonSecretCloudEvidence(value:unknown):Record<string,unknown>|null{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:null;}
function writeReceipt(body:LiveProofReceiptBody):void{const receiptHash=sha256Hex(canonicalJson(body));writeFileSync(RECEIPT_PATH,`${JSON.stringify({...body,receiptHash},null,2)}\n`,'utf8');}
function baseReceipt(plan:LiveGcpProofPlan):ReceiptBase{return{schemaVersion:'prooffleet.gcp-live-proof.v3',sourceRevision:plan.sourceRevision,executionIdentity:plan.executionIdentity,credentialEvidence:null,executionCredentialBindingHash:null,projectId:plan.projectId,region:plan.region,cloudRunService:plan.serviceName,firestoreCollection:plan.collection,operationId:plan.operation.operationId,generatedAt:new Date().toISOString()};}
function complete(base:ReceiptBase,outcome:ProofOutcome,reason:string,cloudRun:Record<string,unknown>|null,firestore:Record<string,unknown>|null):LiveProofReceiptBody{return{schemaVersion:base.schemaVersion,sourceRevision:base.sourceRevision,executionIdentity:base.executionIdentity,credentialEvidence:base.credentialEvidence,executionCredentialBindingHash:base.executionCredentialBindingHash,projectId:base.projectId,region:base.region,cloudRunService:base.cloudRunService,firestoreCollection:base.firestoreCollection,operationId:base.operationId,generatedAt:base.generatedAt,outcome,reason,cloudRun,firestore};}
function readCredentialEvidence(plan:LiveGcpProofPlan):GoogleWifCredentialEvidence{const credentialPath=process.env.GOOGLE_APPLICATION_CREDENTIALS?.trim();if(!credentialPath)throw new Error('GOOGLE_APPLICATION_CREDENTIALS is missing after WIF authentication');return parseGoogleWifCredentialEvidence(readFileSync(credentialPath,'utf8'),plan.wifProvider,plan.wifServiceAccount);}
async function runLiveProof(plan:LiveGcpProofPlan,credentialEvidence:GoogleWifCredentialEvidence):Promise<LiveProofReceiptBody>{const executionCredentialBindingHash=bindExecutionToCredential(plan.executionIdentity,credentialEvidence);const base:ReceiptBase={...baseReceipt(plan),credentialEvidence,executionCredentialBindingHash};const cloudRun=new CloudRunAdapter({projectId:plan.projectId,region:plan.region,serviceName:plan.serviceName,sourceRevision:plan.sourceRevision});const cloudReadback=await cloudRun.readback();const cloudEvidence=nonSecretCloudEvidence(cloudReadback.evidence);if(!cloudReadback.ok)return complete(base,'BLOCKED_BY_MISSING_EVIDENCE',`Cloud Run authoritative readback unavailable: ${cloudReadback.detail}`,null,null);if(cloudEvidence?.parserContract!=='prooffleet.cloudrun-readback.v2'||cloudEvidence?.sourceRevisionMatchesExpected!==true)return complete(base,'BLOCKED_BY_MISSING_EVIDENCE','Cloud Run provider response did not satisfy the exact parser/source identity contract.',cloudEvidence,null);if(!plan.mutationApproved)return complete(base,'BLOCKED_BY_MISSING_EVIDENCE','Explicit workflow-dispatch confirmation for the Firestore proof write is missing.',cloudEvidence,null);const store=await createRealFirestoreEffectStore({GCP_PROJECT_ID:plan.projectId,PROOFFLEET_FIRESTORE_COLLECTION:plan.collection,PROOFFLEET_SOURCE_REVISION:plan.sourceRevision});if(!store)return complete(base,'BLOCKED_BY_MISSING_EVIDENCE','Real Firestore effect store could not be constructed from ADC/configuration.',cloudEvidence,null);const consent=new ConsentEngine();const request=consent.createRequest(plan.operation,'HIGH','Explicit GitHub workflow_dispatch live-proof write.');const grant=consent.respond(request.requestId,'APPROVED',`github-execution:${plan.executionIdentity.identityHash.slice(0,24)}`,'Owner-triggered workflow supplied the exact live-proof confirmation phrase.');if(!grant)throw new Error('explicit live-proof consent grant was not created');const executor=new FirestoreOperatorExecutor(store,plan.sourceRevision,consent);const result=await executor.execute(plan.operation,grant);const firestoreEvidence={status:result.status,sourceKind:result.sourceKind??null,sourceRevision:result.sourceRevision??null,readback:nonSecretCloudEvidence(result.readbackEvidence)};if((result.status==='applied'||result.status==='already_applied')&&result.sourceKind==='FIRESTORE_READBACK'&&result.sourceRevision===plan.sourceRevision)return complete(base,'OBSERVED','Matching run-scoped WIF credential configuration, Cloud Run source identity and operation-bound Firestore effect were authoritatively observed.',cloudEvidence,firestoreEvidence);return complete(base,result.status==='failed'?'CONTRADICTED':'BLOCKED_BY_MISSING_EVIDENCE',result.detail??'Firestore operation did not produce matching authoritative readback evidence.',cloudEvidence,firestoreEvidence);}
async function main():Promise<void>{const plan=buildLiveGcpProofPlan(process.env);let credentialEvidence:GoogleWifCredentialEvidence;try{credentialEvidence=readCredentialEvidence(plan);}catch(error){writeReceipt(complete(baseReceipt(plan),'BLOCKED_BY_MISSING_EVIDENCE',`WIF credential evidence rejected fail-closed: ${error instanceof Error?error.message:String(error)}`,null,null));return;}writeReceipt(await runLiveProof(plan,credentialEvidence));}
const invokedAsScript=process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1];if(invokedAsScript){main().catch((error)=>{process.stderr.write(`[gcp-live-proof] fatal: ${error instanceof Error?error.stack??error.message:String(error)}\n`);process.exit(1);});}
